version: '3.1'

services:

  my_mongo_db:
    image: mongo:6.0
    ports:
      - 27017:27017

  my_maria_db:
    image: mariadb:10.6.14
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=$MARIADB_ROOT_PASSWORD

  my_express:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000:4000
    environment:
      - MONGO_DB_HOST=my_mongo_db

      - MARIADB_HOST=my_maria_db
      - MARIADB_USER=root
      - MARIADB_PASSWORD=$MARIADB_ROOT_PASSWORD
    
  